# Here is where I set the routing, based on pattern matching on "path".
# Note: Zuul is aware of Eureka, and for routing I just need
# to specify the application name (ie the "spring.application.name"
# registered on eureka, which is "service" from the service module
# in this case), and so would do automatically load balancing.
# However, the application "frontend" is not registered on Eureka,
# so need to provide an explicit URL for it.

zuul:
  routes:
    service:
      path: /service/**
    frontend:
      path: /**
      url: http://frontend/


eureka:
  instance:
    preferIpAddress: true
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/