
# By default, it would bind to localhost.
# But inside a Docker image, localhost would point to the image itself,
# and not the Docker image in which RabbitMQ is running.
spring:
  rabbitmq:
    host: rabbitmq