version: '3.3'

services:

  # The Gateway Zuul will be the ONLY Docker instance
  # that does open a port accessible from outside the
  # Docker network.

  zuul:
    build:
      context: ./zuul
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    depends_on:
        - eureka

  eureka:
    build:
      context: ./eureka
      dockerfile: Dockerfile


  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile

  postgres:
    image: "postgres:10"

  service_0:
     build:
        context: ./service
        dockerfile: Dockerfile
     environment:
        - TSDES_SERVICE_ID=A
     depends_on:
        - zuul
        - postgres

  service_1:
     build:
        context: ./service
        dockerfile: Dockerfile
     environment:
        - TSDES_SERVICE_ID=B
     depends_on:
        - zuul
        - postgres

  service_2:
     build:
        context: ./service
        dockerfile: Dockerfile
     environment:
        - TSDES_SERVICE_ID=C
     depends_on:
        - zuul
        - postgres


