jsf:
  project-stage: development

spring:
  jpa:
    # just for debugging
    show-sql: true
  session:
    # specify how sessions should be stored.
    # here we are saying to use an in-memory hash map
    store-type: hash_map

# make sure to integrate the security mechanism with the
# current session of the user.
# When a user gets authenticated, Spring Security will create
# a new HTTP session (based on cookies) for it.
security:
  sessions: ALWAYS

