
# the name here will be important for Discovery, as to determine
# the same "service" among different replicated running instances

spring:
  application:
    name: producer-server
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        instanceId: ${spring.application.name}:${random.value}
