server:
  port: 8080



spring:
  application:
    name: consumer-server
  cloud:
    consul:
      host: discovery
      port: 8500
      discovery:
         instanceId: ${spring.application.name}:${random.value}

