jsf:
  projectStage: Production

# Note: no need to specify URL of database, as Heroku will
# automatically set environmental variables used by Spring

spring:
  datasource:
    driver-class-name: "org.postgresql.Driver"
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: "update"

