version: '3.3'

services:

  # All services here are going to be accessible from the localhost,
  # as binding them to different TCP ports.

  discovery:
    image: "consul:1.8"
    environment:
      - CONSUL_LOCAL_CONFIG={"log_level":"info"}
    ports:
      - "8500:8500"

  consumer:
    build:
        context: ./discovery-consumer
        dockerfile: Dockerfile
    ports:
       - "9000:8080"
    depends_on:
       - discovery

  # Starting 3 different instances of the same service.
  # Going to use an environment variable to distinguish them

  producer_0:
     build:
        context: ./discovery-producer
        dockerfile: Dockerfile
     ports:
        - "9001:8080"
     environment:
        - PRODUCER_ID=A
     depends_on:
        - discovery

  producer_1:
     build:
        context: ./discovery-producer
        dockerfile: Dockerfile
     ports:
        - "9002:8080"
     environment:
        - PRODUCER_ID=B
     depends_on:
        - discovery

  producer_2:
     build:
        context: ./discovery-producer
        dockerfile: Dockerfile
     ports:
        - "9003:8080"
     environment:
        - PRODUCER_ID=C
     depends_on:
        - discovery

