version: '3.3'

services:
  rabbitmq:
    image:  "rabbitmq:3"

  sender:
    build:
        context: ./sender
        dockerfile: Dockerfile
    ports:
       - "9000:8080"
    depends_on:
       # do not start this image until RabbitMQ is started
       - rabbitmq

  # Starting the same service twice.
  # To access it from localhost, need to bind them
  # to different TCP ports.


  receiver_0:
     build:
        context: ./receiver
        dockerfile: Dockerfile
     ports:
        - "9001:8080"
     depends_on:
        - rabbitmq

  receiver_1:
    build:
        context: ./receiver
        dockerfile: Dockerfile
    ports:
        - "9002:8080"
    depends_on:
        - rabbitmq